apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-example
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/node-example-gke/frontend:v7
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: WEBSOCKET_HOST
          value: ws://104.196.137.73
        ports:
        - containerPort: 3001
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /status?deployment=1
            port: 3001
          initialDelaySeconds: 15
          timeoutSeconds: 1
