apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/node-example-gke/frontend:v9
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: WEBSOCKET_HOST
          value: /
        - name: WEBSOCKET_PATH
          value: /websocket/websocket
        ports:
        - containerPort: 3001
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /status?livenessProbe=1
            port: 3001
          initialDelaySeconds: 15
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /status?readinessProbe=1
            port: 3001
          initialDelaySeconds: 15
          timeoutSeconds: 1
