apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    serviceloadbalancer/lb.aclMatch: "-i /"
  labels:
    app: node-example
    name: frontend
    visualize: 'true'
spec:
  ports:
  - name: frontend-service
    port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    name: frontend
