apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: node-example
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - name: frontend-service
    port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    app: node-example
    tier: frontend
