apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    serviceloadbalancer/lb.aclMatch: "-i /"
  labels:
    app: frontend
spec:
  ports:
  - name: frontend-service
    port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    app: frontend
