apiVersion: v1
kind: ReplicationController
metadata:
  name: service-loadbalancer
  labels:
    app: node-example
    name: service-loadbalancer
    version: v1
    visualize: 'true'
spec:
  replicas: 2
  selector:
    app: node-example
    name: service-loadbalancer
    version: v1
    visualize: 'true'
    uses: frontend, websocket
  template:
    metadata:
      labels:
        app: node-example
        version: v1
    spec:
      nodeSelector:
        role: loadbalancer
      containers:
      - image: gcr.io/google_containers/servicelb:0.4
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        name: haproxy
        ports:
        # All http services
        - containerPort: 80
          hostPort: 80
          protocol: TCP
        # haproxy stats
        - containerPort: 1936
          hostPort: 1936
          protocol: TCP
        args:
        - --default-return-code=200
