apiVersion: v1
kind: Service
metadata:
  name: haproxy
  labels:
    app: node-example
    name: service-loadbalancer
    visualize: 'true'
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    name: service-loadbalancer
