apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: websocket
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: websocket
    spec:
      containers:
      - name: websocket
        image: gcr.io/node-example-gke/websocket:v6
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: WEBSOCKET_PATH
          value: /websocket
        ports:
        - containerPort: 3002
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /status?livenessProbe=1
            port: 3002
          initialDelaySeconds: 15
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /status?readinessProbe=1
            port: 3002
          initialDelaySeconds: 15
          timeoutSeconds: 1
