apiVersion: v1
kind: Service
metadata:
  name: websocket
  labels:
    app: node-example
    tier: websocket
spec:
  type: LoadBalancer
  sessionAffinity: true
  cookieStickySession: true
  ports:
  - name: websocket-service
    port: 80
    protocol: TCP
    targetPort: 3002
  selector:
    app: node-example
    tier: websocket
