apiVersion: v1
kind: Service
metadata:
  name: websocket
  annotations:
    serviceloadbalancer/lb.aclMatch: "-i /socket.io"
    # Enable sticky-ness on "SERVERID"
    serviceloadbalancer/lb.cookie-sticky-session: "true"
  labels:
    app: websocket
spec:
  ports:
  - name: websocket-service
    port: 80
    protocol: TCP
    targetPort: 3002
  selector:
    app: websocket
