apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: node-example
    role: master
    name: redis
    visualize: 'true'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-example
        role: master
        name: redis
        visualize: 'true'
    spec:
      containers:
      - name: master
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
