apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    app: node-example
    name: redis
    role: master
    visualize: 'true'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-example
        name: redis
        role: master
        visualize: 'true'
    spec:
      containers:
      - name: master
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
