apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: node-example
    role: master
    name: redis
    visualize: 'true'
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis
    role: master
